# Test configuration for the LoggingEngine test suite

[test.integration]
# Integration test settings
timeout = "300s"
parallel = true
nocapture = true

[test.benchmarks] 
# Benchmark test settings
timeout = "600s"
measurement_time = "10s"
warm_up_time = "3s"
sample_size = 100

[test.property]
# Property-based test settings  
timeout = "120s"
cases = 1000
max_shrink_iters = 10000

[test.e2e]
# End-to-end test settings
timeout = "600s"
parallel = false  # E2E tests should run sequentially
nocapture = true

[test.performance]
# Performance test thresholds
max_avg_latency_us = 1.0
max_p99_latency_us = 5.0
min_throughput_ops_per_sec = 100000.0

[test.trading]
# Trading scenario test settings
order_processing_timeout_us = 50.0
risk_check_timeout_us = 5.0
execution_timeout_us = 20.0

[test.environment]
# Test environment configuration
log_level = "INFO"
enable_tracing = true
skip_slow_tests = false
skip_redis_tests = false
skip_kafka_tests = false

[test.resources]
# Resource limits for tests
max_memory_mb = 1024
max_cpu_cores = 4
temp_dir = "/tmp/logging_engine_tests"
