groups:
  - name: logging-engine-alerts
    rules:
      - alert: HighLoggingLatency
        expr: logging_latency_p99_microseconds > 500
        for: 30s
        labels:
          severity: critical
          component: ultra-logger
        annotations:
          summary: "Logging latency is critically high"
          description: "P99 logging latency is {{ $value }}µs, exceeding the 500µs threshold"

      - alert: LogBufferOverflow
        expr: increase(logging_buffer_overflows_total[5m]) > 0
        for: 0s
        labels:
          severity: critical
          component: ultra-logger
        annotations:
          summary: "Log buffer overflow detected"
          description: "{{ $value }} buffer overflows in the last 5 minutes"

      - alert: HighLogDropRate
        expr: rate(logging_entries_dropped_total[5m]) > 10
        for: 1m
        labels:
          severity: warning
          component: ultra-logger
        annotations:
          summary: "High log entry drop rate"
          description: "Dropping {{ $value }} log entries per second"

      - alert: LogTransportFailures
        expr: rate(logging_transport_errors_total[5m]) > 1
        for: 2m
        labels:
          severity: warning
          component: log-transport
        annotations:
          summary: "Log transport experiencing failures"
          description: "Transport error rate: {{ $value }} errors/sec"

      - alert: HighBufferUtilization
        expr: logging_buffer_utilization_percent > 90
        for: 2m
        labels:
          severity: warning
          component: ultra-logger
        annotations:
          summary: "Log buffer utilization is high"
          description: "Buffer utilization is {{ $value }}%, approaching overflow threshold"

      - alert: LoggingSystemDown
        expr: up{job="logging-engine"} == 0
        for: 30s
        labels:
          severity: critical
          component: logging-engine
        annotations:
          summary: "Logging engine is down"
          description: "Logging engine instance {{ $labels.instance }} is not responding"
