{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ultra-logging-engine.fullname" . }}-grafana-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ultra-logging-engine.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ include "ultra-logging-engine.fullname" . }}-prometheus:9090
        isDefault: true
        editable: true
      
      {{- if .Values.redis.enabled }}
      - name: Redis
        type: redis-datasource
        access: proxy
        url: redis://{{ .Values.redis.host | default "redis" }}:{{ .Values.redis.port | default 6379 }}
        jsonData:
          client: "standalone"
        secureJsonData:
          password: "{{ .Values.redis.password | default "" }}"
      {{- end }}
      
      {{- if .Values.kafka.enabled }}
      - name: Kafka
        type: kafka-datasource  
        access: proxy
        url: {{ (index .Values.kafka.brokers 0) | default "kafka:9092" }}
        jsonData:
          bootstrapServers: {{ .Values.kafka.brokers | toJson }}
          topic: "{{ .Values.kafka.topic | default "trading-logs" }}"
      {{- end }}
{{- end }}
