{{- if and .Values.grafana.enabled .Values.grafana.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ultra-logging-engine.fullname" . }}-grafana-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ultra-logging-engine.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
  {{- if .Values.grafana.persistence.storageClass }}
  storageClassName: {{ .Values.grafana.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
